import { useStore } from '../store/useStore';

export const getAiResponse = async (input: string, image?: string) => {
    const controller = new AbortController();
    // 60s timeout — Gemini + Google Search can be slow on image analysis
    const timeoutId = setTimeout(() => controller.abort(), 60_000);

    // Client-side exact match cache bypass for frequent foods
    if (!image && input && input.trim()) {
        const searchStr = input.toLowerCase().trim();
        const { favorites, dailyLog, historicalDays } = useStore.getState();

        const findMatch = (entries: any[]) => entries.find(e => {
            if (!e.name) return false;
            const rawName = e.name.toLowerCase();
            // Exact match
            if (rawName === searchStr) return true;
            // Match without the *Title* generated by AI
            const descMatch = rawName.match(/^\*[^*]+\*\s*(.*)$/);
            if (descMatch && descMatch[1].trim() === searchStr) return true;
            // Match just the title part
            if (descMatch && rawName.match(/^\*([^*]+)\*/)?.[1].trim() === searchStr) return true;
            return false;
        });

        const favMatch = findMatch(favorites);
        if (favMatch) {
            console.log("CACHE HIT: Found in Favorites!");
            return { type: 'success', data: { kcal: favMatch.kcal, protein: favMatch.protein, carbs: favMatch.carbs, fat: favMatch.fat, name: favMatch.name } };
        }

        const dailyMatch = findMatch(dailyLog);
        if (dailyMatch) {
            console.log("CACHE HIT: Found in Today's Log!");
            return { type: 'success', data: { kcal: dailyMatch.kcal, protein: dailyMatch.protein, carbs: dailyMatch.carbs, fat: dailyMatch.fat, name: dailyMatch.name } };
        }

        for (const hDay of historicalDays) {
            const hMatch = findMatch(hDay.entries);
            if (hMatch) {
                console.log("CACHE HIT: Found in History!");
                return { type: 'success', data: { kcal: hMatch.kcal, protein: hMatch.protein, carbs: hMatch.carbs, fat: hMatch.fat, name: hMatch.name } };
            }
        }
    }

    try {
        const res = await fetch('/api/analyze', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ input, image }),
            signal: controller.signal,
        });

        clearTimeout(timeoutId);

        if (!res.ok) {
            const errorText = await res.text();
            console.error("API Error", errorText);
            try {
                const errorJson = JSON.parse(errorText);
                return { type: 'error', error: errorJson.error || errorJson.message || `Server Error ${res.status}` };
            } catch {
                if (res.status === 504) return { type: 'error', error: 'Vercel Timeout (Model too slow, >10s)' };
                return { type: 'error', error: `Server Error ${res.status}: ${errorText.substring(0, 100)}` };
            }
        }

        return await res.json();
    } catch (e: any) {
        clearTimeout(timeoutId);
        if (e.name === 'AbortError') {
            console.warn("AI request timed out or was aborted (screen lock?)");
            return { type: 'error', error: 'Request timed out (60s)' };
        }
        console.error("Network Error", e);
        return { type: 'error', error: `Network Error: ${e.message || 'Failed to fetch'}` };
    }
};
